<main id="cv" class="container">
	<section>
		<article>
			<h2>Compétences</h2>
			<ul>
				<li><span>Illustrator</span></li>
				<li>Photoshop</li>
				<li>InDesign</li>
				<li>SketchUp</li>
				<li>Autocad</li>
				<li>Corel Draw</li>
				<li>Powerpoint</li>
				<li>Excel</li>
			</ul>
			<h2>Langues</h2>
			<ul>
				<li>Anglais</li>
				<small>Courant (Niveau C1)</small>
				<li>Allemand</li>
				<small>Intermédiaire (Niveau B1)</small>
			</ul>
		</article>
		<article>
			<h2 class="display-div h2-selected">Expériences</h2>
			<h2 class="display-div underline">Diplomes & Formations</h2>
			<div class="cv-content-exp">
				<p class="formation-date">Octobre 2016 à Décembre 2017</p>
				<section>
					<i class="fas fa-circle fa-xs"></i>
					<h3 class="formation-title">Décoratrice / Chargée de communication visuelle chez ALINEA</h3>
					<p class="formation">Création de nouvelles ambiances, entretien du magasin, veille concurentielle, réalisation de cahiers des tendances, application des préconisations du siège, mise et place d’opérations commerciales, création d’ILV et de PLV, mise en place des PLV, connaissance des différents supports de communication, merchandising.</p>
				</section>
				<p class="formation-date">Mars 2016</p>
				<section>
					<i class="fas fa-circle fa-xs"></i>
					<h3 class="formation-title">Assistante visuel merchandising chez Sonia Rykiel</h3>
					<p class="formation"><em>Stage</em> - Display, Guideline, Showroom, suivi des boutiques.</p>
				</section>				
			</div>			
			<div class="cv-content-form hide">
				<p class="formation-date">2015 / 2016</p>
				<p class="formation"><span>FCIL Visuel Merchandisig</span> au Lycée Abbé Grégoire</p>
				<p class="formation-date">2012 / 2015</p>
				<p class="formation"><span>Bi-Licence LLCE Anglais / Histoire de l’art</span> à l’Institut Catholique de Paris</p>
			</div>
		</article>
	</section>
</main>