<main id="index" class="container">
	<section>
		<h1 id="main-title">Karen Chaudot</h1>
		<p>Décoratrice - Visual Merchandiser</p>
		<p>Passionnée de déco, c’est finalement le merchandising qui aura eu raison de moi.</p> 
		<p>J’aime devoir ré-inventer le magasin chaque jour et innover pour le rendre plus attractif.</p>
		<img id="mainphoto" src="templates/img/Photo_CV2.jpg" alt="Photo de Karen Chaudot">
	</section>
	<div>
		<a href="<?= $www ?>/cv" class="underline">Cv</a>
		<i class="fas fa-circle fa-xs"></i>
		<a href="<?= $www ?>/book" class="underline">Book</a>
		<i class="fas fa-circle fa-xs"></i>
		<a href="<?= $www ?>/inspiration" class="underline">Inspirations</a>
		<i class="fas fa-circle fa-xs"></i>
		<a href="<?= $www ?>/contact" class="underline">Contact</a>
	</div>
